### PR TITLE
Add test cases and freebsd kmem for ZSTD

### PR DESCRIPTION
**Pull request by allanjude**
This adds test cases for the ZSTD compression header, to ensure it is saved and restored correctly.

It adds another case to make sure ZSTD compression survives replication correctly.

Latestly, it splits the OS specific ZSTD bits into separate files for Linux and FreeBSD, so that FreeBSD can use kmem_cache rather than the Linux vmem pool.

### CODE REVIEW

**Comment by c0d3z3r0** [comment]
tbh I don't think we should do os splitting that way, effectively duplicating much code that has to be maintained then. further, we should concentrate on fixing bugs an merging the current version and do improvements later.

@behlendorf @Ornias1993 opinions?

**Comment by allanjude** [comment]
> 
> 
> tbh I don't think we should do os splitting that way, effectively duplicating much code that has to be maintained then. further, we should concentrate on fixing bugs an merging the current version and do improvements later.
> 
> @behlendorf @Ornias1993 opinions?

I kept all of the common bits the same in zstd.c

**Comment by c0d3z3r0** [comment]
> But about splitting:
> When there is duplicate code, thats basically a no-no and mistakes waiting to happen.
> But if we just split code based on OS and prevent duplicate code, it might make it easier for the different platforms to, simply put, "keep their their house clean"

^This, and we will never get this merged when we add more and more to this PR because each new feature needs a review.

Further, the whole point of that split seems to be using a different allocator in FreeBSD. That can be achieved easier by making the allocator configurable in module/zstd/zstd.c (well, at actually already is) and only have the allocator code in /os. Still, this change should be a separate PR later, when zstd is merged.

**Comment by BrainSlayer** [comment]
i already commented in the pull request of alan what i think, but it was ignored so far. i think the whole split is uneccessary. if the freebsd allocator is perfect, the performance will be equal at best to my implementation, but from the way a cached memory allocator in freebsd and linux works it will also waste much more resources. the good thing in my solution is that the maximum consumption of memory is fixed and calculatable and it wasnt just made as workaround for a missing allocator. linux has a cached slab allocator too, but it was made for performance reasons. since alan has not yet done any benchmark on his splitted allocation solution which compares it with the mempool allocator we made here, i see no reason to merge it. so before going that weired way there must be a proof that there is any benefit in using the standard system allocator of freebsd

and in addition. test cases are not comparable anymore. both codepaths may have different bugs.

**Comment by allanjude** [comment]
Note: This pull request is different than the original one. It uses the existing ZFS zio caches, except for in the very extreme cases (very large blocks at very high compression levels).

If it is preferred, move the split into a separate branch for now, and revisit it after.

**Comment by BrainSlayer** [comment]
@allanjude the zfs zio caches are verified to be not working for our usecase. allocation is too slow. it will fail the test cases due time limitation. please trust me or us. there was a real good reason to write a own allocator and this one will perfectly work with freebsd too. there is no reason to introduce another one which is less efficient in memory consumption and handling and if you think different. please do a benchmark comparisation for writing files with standard zfs compression and compare memory consumption and performance. that all what matters. i dont think that there is a faster solution than i did (except for micro optimizations)

**Comment by BrainSlayer** [comment]
there are never enough tests. i'm fine with that

**Comment by allanjude** [comment]
> 
> 
> @BrainSlayer Indeed, we (the two of us) spend... what was it... 3-4 weeks, puzzling with different performance tests and test results to get to the current design running as smoothly as it does...
> 

Note: I did not change any of the code you wrote, I just made it not be used on FreeBSD, which does not suffer from the issues you ran into. It does however, prefer to use the UMA allocator, because it avoids fragmentation, and in FreeBSD, is moving to a new design called SMR (Safe Memory Reclaim): https://svnweb.freebsd.org/base?view=revision&revision=357314

But we can revisit this FreeBSD specific code later.

> I think we agree that before the suggested changes pass the tests suite and improve anything, they should not be merged (yet)...
> 
> I'm okey with cherrypicking the tests and I think we are all in agreement those can be merged +1

I've force pushed this branch without that change for now.

**Comment by allanjude** [comment]
> 
> 
> > Note: I did not change any of the code you wrote, I just made it not be used on FreeBSD, which does not suffer from the issues you ran into.
> 
> Did you test it using the test suite? Because we never figured out for 100% use what was the cause of that one test hitting timelimit to begin with... As in: We know what code caused it, but not why and if it would be OS dependent...
> So I think it's a little quick to point out that FreeBSD doesn't have said issues, unless you tested it... in that case: you're right ofcourse!
> 
> > I've force pushed this branch without that change for now.
> > I noticed, thanks... Looks nice +1

Do you remember which specific test?

**Comment by behlendorf** [comment]
If a different allocator makes more sense for FreeBSD I don't think that's problem.  But I agree, we should get the current code merged first and follow up with that kind of optimization as needed in a new PR.

**Comment by BrainSlayer** [comment]
@behlendorf @allanjude  i agree if it makes more sense. but if the freebsd allocator is slower than the one we created it doesnt make sense and so far it seem that this hasnt been tested or compared in any way. so what i'm missing here is the reason. so if allan can proof that his approach for freebsd works as good as the approach we did under all conditions, i'm fine with splitting the code for the memory allocation. but even with identical results spliting is questionable since it would make code maintainance more complicated. the performance of allocating memory (and reclaiming it i f neccessary) is a very important point here.

**Pull request merged**
