### PR TITLE
Rename module/zstd/zstd.c to zfs_zstd.c

### PR DESCRIPTION
**Pull request by allanjude**
So we can call the zstd lib file zstd.c, and our code zfs_zstd.c

This is a cleaner solution, and avoids problems with the BSD makefiles too

Signed-off-by: Allan Jude <allanjude@freebsd.org>

### CODE REVIEW

**Comment by c0d3z3r0** [comment]
> This is a cleaner solution

erm, I guess we have a different understanding what is "clean" :D I don't like having the files just distinguished by prefixes. A subfolder `lib/` ist way more clear.

@Ornias1993 your opinion?

So, I don't like that single-makefile-approach anyways. Can't zstd have it's own Makefile.bsd?

**Comment by allanjude** [comment]
Maybe the simpliest solution:
Keep zstd in lib/
but keep my rename of our code to 'zfs_zstd.c' so that we don't have 2 files called zstd.c in almost the same path (it makes the CFLAGS stuff hard, and is just confusing)

**Comment by allanjude** [comment]
I see the fix you committed to the main PR, I'll make sure that works on BSD, and it is fine with me.

**Comment by c0d3z3r0** [comment]
> Maybe the simpliest solution:
> Keep zstd in lib/

ah, oh lol. no idea why I didn't have that idea. I'd just name 'our' `zstd.c` `zzstd.c`, like the module name, but I'd be fine with `zfs_zstd-c` as well

**Comment by allanjude** [comment]
What you have now is fine, as long as the 2 files don't have the same name

**Pull request closed without merging**
